---
- name: sovbox
  hosts: sovbox
  become: yes

  roles:
    - sovbox
    - { name: bitcoind, tags: ['bitcoind'] }
    - { name: electrumx, tags: ['electrumx'] }
    - { name: btc-rpc-explorer, tags: ['btc-rpc-explorer'] }
