---
-
- name: Disable empty password login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"

- name: restart sshd
  systemd:
    name: ssh
    state: restarted
