
# @todo move this to the right roles

system_apt_packages:
      - aptitude
      - git
      - build-essential
      - autoconf
      - libtool
      - pkg-config
      - libboost-all-dev
      - libssl-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libevent-dev
      - python3-setuptools
      - python3-pip
      - libbz2-dev
      - liblz4-dev
      - libsnappy-dev

