---
-
- name: Disable empty password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
  tags:
  - sovbox
  
- name: restart ssh
  systemd:
    name: ssh
    state: restarted
    enabled: yes
  tags:
  - sovbox

- name: Upgrade packages
  apt:
    upgrade: dist
    update-cache: yes

- name: Install system packages
  apt: pkg={{ item }}
  with_items: "{{ system_apt_packages }}"
