---
-
- name: Firewall 
  ufw:
    port: '50002'
    rule: limit
    proto: tcp
    state: enabled
  tags:
  - firewall
  - electrumx
    
- name: Install packages for electrumx
  apt: pkg={{ item }}
  with_items: "{{ apt_packages }}"
  tags:
  - apt
  - electrumx

- name: create electrumx user
  user:
    name: electrumx
    home: /home/electrumx
    state: present
  tags:
    - systemd
    - electrumx

- name: electrumx, pip install rocksdb
  shell: pip3 install python-rocksdb
  tags:
    - electrumx

- name: Git clone electrumx repo
  git:
    repo: https://github.com/kyuupichan/electrumx
    dest: /home/electrumx/electrumx
    version: 1.12.0
    ## https://themerkle.com/electrumx-secretly-switches-to-bitcoin-cash-as-their-main-chain/
  tags:
    - electrumx

- name: Build and install electrumx
  shell: python3 setup.py install
  args:
    chdir: /home/electrumx/electrumx
  tags:
    - electrumx
    
- name: electrum db
  file:
    path: /var/lib/electrum-db
    owner: electrumx
    state: directory
  tags:
    - systemd
    - electrumx
        
- name: copy Electrumx systemd conf
  copy:
    src: /home/electrumx/electrumx/contrib/systemd/electrumx.service
    dest: /etc/systemd/system/electrumx.service
    remote_src: yes
  tags:
    - systemd
    - electrumx

- name: create /etc/electrumx
  file:
    state: directory
    path: /etc/electrumx
  tags:
    - electrumx
    - etc

- name: extract rpc user and password from /etc/bitcoin/bitcoin.conf
  slurp:
    src: /etc/bitcoin/bitcoin.conf
  register: bitcoinconf
  tags:
  - rpc
  - electrumx
  - rpcelx

- name: get password to connect to bitcoind
  set_fact:
    rpc_pass: "{{ bitcoinconf['content'] | b64decode | regex_search('password=(.*)') | regex_replace('password=', '') }}"
  tags: 
  - rpc
  - electrumx
  - rpcelx
  
- name: get username to connect to bitcoind
  set_fact:
    rpc_user: "{{ bitcoinconf['content'] | b64decode | regex_search('user=(.*)') | regex_replace('user=', '') }}"
  tags: 
  - rpc
  - electrumx
  - rpcelx

- name: copy electrum conf
  template:
    src: files/electrumx.conf.j2
    dest: /etc/electrumx.conf
  tags:
    - etc
    - rpc
    - electrumx
    - rpcelx



- name: electrumx generate ssl keys
  shell: openssl genrsa -out server.key 2048
  args:
    chdir: /etc/electrumx
    creates: /etc/electrumx/server.key
  tags:
    - electrumx
    - elxssl

- name: electrumx generate ssl keys
  shell: yes '' | openssl req -new -key server.key -out server.csr
  args:
    chdir: /etc/electrumx
    creates: /etc/electrumx/server.csr
  tags:
    - electrumx
    - elxssl

- name: electrumx generate ssl keys
  shell: openssl x509 -req -days 1825 -in server.csr -signkey server.key -out server.crt
  args:
    chdir: /etc/electrumx
    creates: /etc/electrumx/server.crt
  tags:
    - electrumx
    - elxssl

- name: Set electrumx up as daemon, load at boot
  systemd:
    name: electrumx
    state: restarted
    enabled: yes
    daemon_reload: yes
  tags:
    - systemd
    - electrum
    - rpc
    - rpcelx

